### ISSUE TITLE
Is it possible to drop dependency on logger version 2.066?

### ISSUE THREAD

**Issue by drug007** [d-gamedev-team/gfm#137]
The `logger` package version `2.066` instead of std/experimental/logger has std/historical/logger file structure now and it prevents from successful compiling.

**Comment by p0nce** [comment]
Yes it was renamed on purpose to avoid an unsolvable problem otherwise: https://github.com/burner/logger/issues/22

GFM is compatible up to DMD frontend 2.066, std.experimental.logger only exist in 2.067.

To be compatible with all frontends, include it like that:
```d
static if( __VERSION__ >= 2067 )
    import std.experimental.logger;
else
    import std.historical.logger;
```


else to be only compatible with DMD 2.067+, include it normally:
```
import std.experimental.logger;
```

Once GFM drops compatibility with 2.066 frontend, the logger dependency won't be needed anymore.

**Comment by drug007** [comment]
Thanks!
